IntegratedAttendanceSystem/IntegratedAttendanceSystem/Controllers/EmployeeGroupPolicyController.cs
using IntegratedAttendanceSystem.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace IntegratedAttendanceSystem.Controllers
{
    public class EmployeeGroupPolicyController : Controller
    {
        /// <summary>
        /// This variable is use to assign the hosted url of web api.
        /// it may vary according to systems.
        /// </summary>
        string APIUrl = ConfigurationManager.AppSettings["APIURL"].ToString();
        // GET: EmployeeGroupPolicy
        public ActionResult EmployeeGroupPolicy()
        {
            try
            {

            }
            catch (Exception ex)
            {
                ExceptionLogging.SendErrorToText(ex);
            }
            return View();
        }
        public ActionResult CreateEmployeeGroupPolicy()
        {
            try
            {

            }
            catch (Exception ex)
            {
                ExceptionLogging.SendErrorToText(ex);
            }
            return View();
        }

        //// Get all company
        public JsonResult ListAllShift()
        {
            EmployeeGroupPolicy jm = new EmployeeGroupPolicy();
            List<Shift_list> lst = new List<Shift_list>();
            try
            {
                string userName = Session["UserName"].ToString();
                string CompanyCode = Session["CompanyCode"].ToString();;
                //jm.LastModifiedBy = userName;
                Shift_list cm = new Shift_list();
                using (var client = new HttpClient())
                {
                    //Passing service base url  
                    client.BaseAddress = new Uri(APIUrl);
                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    //Sending request to find web api REST service resource GetAllEmployeeGroupPolicys using HttpClient  
                    var res = client.PostAsJsonAsync("EmployeeGroupPolicy/GetShiftList", jm).Result;

                    //Checking the response is successful or not which is sent using HttpClient  
                    if (res.IsSuccessStatusCode)
                    {
                        var lstResponse = res.Content.ReadAsStringAsync().Result;
                        //Deserializing the response recieved from web api and storing into the EmployeeGroupPolicy list  
                        lst = JsonConvert.DeserializeObject<List<Shift_list>>(lstResponse);
                        if (lst.Count > 0)
                        {
                            foreach (Shift_list cms in lst)
                            {
                                cm.ShiftCode = cms.ShiftCode;
                                cm.ShiftName = cms.ShiftName;
                            }
                            return Json(lst.ToList(), JsonRequestBehavior.AllowGet);
                        }
                    }
                    else
                    {
                        return Json("error", JsonRequestBehavior.AllowGet);
                    }
                }
                return Json(lst.ToList(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ExceptionLogging.SendErrorToText(ex);
                ViewBag.Message = "Error occured, contact to administrator";
                return Json("error", JsonRequestBehavior.AllowGet);
            }
        }


        //// Get all Group
        public JsonResult ListAlGroup()
        {
            List<Group_list> lst = new List<Group_list>();
            EmployeeGroupPolicy jpm = new EmployeeGroupPolicy();
            try
            {
                string userName = Session["UserName"].ToString();
                string CompanyCode = Session["CompanyCode"].ToString();;
                //jpm.LastModifiedBy = userName;
                Group_list gm = new Group_list();
                using (var client = new HttpClient())
                {
                    //Passing service base url  
                    client.BaseAddress = new Uri(APIUrl);
                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    //Sending request to find web api REST service resource GetAllEmployeeGroupPolicys using HttpClient  
                    var res = client.PostAsJsonAsync("EmployeeGroupPolicy/GetGroupList", jpm).Result;

                    //Checking the response is successful or not which is sent using HttpClient  
                    if (res.IsSuccessStatusCode)
                    {
                        var lstResponse = res.Content.ReadAsStringAsync().Result;
                        //Deserializing the response recieved from web api and storing into the EmployeeGroupPolicy list  
                        lst = JsonConvert.DeserializeObject<List<Group_list>>(lstResponse);
                        if (lst.Count > 0)
                        {
                            foreach (Group_list gms in lst)
                            {
                                gm.GroupCode = gms.GroupName;
                                gm.GroupName = gms.GroupName;

                            }
                            return Json(lst.ToList(), JsonRequestBehavior.AllowGet);
                        }
                    }
                    else
                    {
                        return Json("error", JsonRequestBehavior.AllowGet);
                    }
                }
                return Json(lst.ToList(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ExceptionLogging.SendErrorToText(ex);
                ViewBag.Message = "Error occured, contact to administrator";
                return Json("error", JsonRequestBehavior.AllowGet);
            }
        }
        //// Get all company
        public JsonResult ListAllCompany()
        {
            EmployeeGroupPolicy jm = new EmployeeGroupPolicy();
            List<Company_list> lst = new List<Company_list>();
            try
            {
                string userName = Session["UserName"].ToString();
                string CompanyCode = Session["CompanyCode"].ToString();;
                //jm.LastModifiedBy = userName;
                Company_list cm = new Company_list();
                using (var client = new HttpClient())
                {
                    //Passing service base url  
                    client.BaseAddress = new Uri(APIUrl);
                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    //Sending request to find web api REST service resource GetAllEmployeeGroupPolicys using HttpClient  
                    var res = client.PostAsJsonAsync("EmployeeGroupPolicy/GetCompanyList", jm).Result;

                    //Checking the response is successful or not which is sent using HttpClient  
                    if (res.IsSuccessStatusCode)
                    {
                        var lstResponse = res.Content.ReadAsStringAsync().Result;
                        //Deserializing the response recieved from web api and storing into the EmployeeGroupPolicy list  
                        lst = JsonConvert.DeserializeObject<List<Company_list>>(lstResponse);
                        if (lst.Count > 0)
                        {
                            foreach (Company_list cms in lst)
                            {
                                cm.CompanyCode = cms.CompanyCode;
                                cm.CompanyName = cms.CompanyName;
                            }
                            return Json(lst.ToList(), JsonRequestBehavior.AllowGet);
                        }
                    }
                    else
                    {
                        return Json("error", JsonRequestBehavior.AllowGet);
                    }
                }
                return Json(lst.ToList(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ExceptionLogging.SendErrorToText(ex);
                ViewBag.Message = "Error occured, contact to administrator";
                return Json("error", JsonRequestBehavior.AllowGet);
            }
        }
        //// Get all department
        public JsonResult ListAlDepartment()
        {
            EmployeeGroupPolicy em = new EmployeeGroupPolicy();
            List<Department_list> lst = new List<Department_list>();
            try
            {
                Department_list dm = new Department_list();

                using (var client = new HttpClient())
                {
                    string userName = Session["UserName"].ToString();
                    string CompanyCode = Session["CompanyCode"].ToString();;
                    //em.LastModifiedBy = userName;
                    //Passing service base url  
                    client.BaseAddress = new Uri(APIUrl);
                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    //Sending request to find web api REST service resource GetAllEmployeeGroupPolicys using HttpClient  
                    var res = client.PostAsJsonAsync("EmployeeGroupPolicy/GetDepartmentList", em).Result;

                    //Checking the response is successful or not which is sent using HttpClient  
                    if (res.IsSuccessStatusCode)
                    {
                        var lstResponse = res.Content.ReadAsStringAsync().Result;

IntegratedAttendanceSystem/IntegratedAttendanceSystem/Views/EmployeeGroupPolicy/EmployeeGroupPolicy.cshtml
@{
    ViewBag.Title = "EmployeeGroupPolicyList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/themes/base/all.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.11.4.js"></script>
    <link href="~/Content/themes/base/accordion.css" rel="stylesheet" />

    @Scripts.Render("~/MyCustomScript/plugins/jquery/jquery.min.js")
    @Scripts.Render("~/mycustomscript/plugins/datatables/jquery.datatables.min.js")
    @Scripts.Render("~/Custom_Script/dist/js/EmployeeGroupPolicyList.js")
    @*@Scripts.Render("~/MyCustomScript/dist/js/AuditLogReports.js")*@
    @*@Scripts.Render("~/MyCustomScript/dist/js/AuditLogReports.js")*@
    @*@Scripts.Render("~/MyCustomScript/dist/js/jobdescription.js")*@
    @section MyScripts {
        <script type="text/javascript">

            $(function () {
                $("#tabs").tabs();
            });

            $(function () {
                $("#accordion").accordion();
            });

            $(document).ready(function () {
                //$("#btnAdd").click(function () {
                //    $('#myModal').modal('show');
                //});
            });
        </script>
    }

    @*======== Date Range ============*@
    @*<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"
                type="text/javascript"></script>
        <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css"
              rel="Stylesheet" type="text/css" />*@
    <script type="text/javascript">
        $(function () {
            $("#txtFrom").datepicker({
                dateFormat: 'dd/mm/yy',
                numberOfMonths: 2,
                onSelect: function (selected) {
                    var dt = new Date(selected);
                    dt.setDate(dt.getDate() + 1);
                    $("#txtTo").datepicker("option", "minDate", dt);
                }
            });
            $("#txtTo").datepicker({
                dateFormat: 'dd/mm/yy',
                numberOfMonths: 2,
                onSelect: function (selected) {
                    var dt = new Date(selected);
                    dt.setDate(dt.getDate() - 1);
                    $("#txtFrom").datepicker("option", "maxDate", dt);
                }
            });
        });
    </script>

    @*======== Date Range ============*@
</head>
<body>
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">

            window.onload = function () {
                alert("Error occured contact to Administrator");
            };
        </script>
    }

    @*<div class="container">
            @if (Session["LangType"].ToString() == "A")
            {
                <h2>@IntegratedAttendanceSystem.Resources.Language.EmployeeGroupPolicyMaster</h2>
            }
            else
            {
                <h2 class="page-header">EmployeeGroupPolicy Master</h2>
            }
        </div>*@

    <h2>@((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.EmployeeGroupPolicy : "Employee Group Policy" )</h2>

    @*<button type="button" class="btn btn-primary" id="btnAdd" href="@Url.Action("EmployeeGroupPolicyMasterEdit","EmployeeGroupPolicyMaster")">Add New</button><br /><br />*@
    @*<a class="btn btn-primary" id="btnAdd">Add New</a>*@
    @*<input type="button" class="btn btn-primary" id="btnAdd" value="Add New" onclick="location.href='@Url.Action("EmployeeGroupPolicyMasterEdit", "EmployeeGroupPolicyMaster")'" />*@
    
    @if (Session["LangType"].ToString() == "A")
    {
        @*<b>@IntegratedAttendanceSystem.Resources.Language.EmployeeGroupPolicyMaster</b>*@
        <input type="button" class="btn btn-primary" id="btnAdd" value="@IntegratedAttendanceSystem.Resources.Language.AddNew" onclick="location.href='@Url.Action("CreateEmployeeGroupPolicy", "EmployeeGroupPolicy")'" />
    }
    else
    {
        <input type="button" class="btn btn-primary" id="btnAdd" value="Add New" onclick="location.href='@Url.Action("CreateEmployeeGroupPolicy", "EmployeeGroupPolicy")'" />
    }

    <table class="table table-bordered table-hover table-striped display nowrap" id="tblEmployeeGroupPolicy" style="width:100%">
        <thead>
            <tr>
                <th id="tblThEdit">
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.Edit : "EDIT" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.Delete : "DELETE" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.GroupID : "Group ID" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.GroupName : "Group Name" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.Company : "Company" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.PermissibleLateArrival : "Permissible Late Arrival" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.PermissibleEarlyDeparture : "Permissible Early Departure" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.MaxWorkingHourInADay : "Maximum Working Hour In A Day" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.IsRoundTheClockWork : "Is Round The Clock Work" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.ConsiderTimeLoss : "Consider Time Loss" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.IsHalfDay : "Is Half Day" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.IsSortLeave: "Is Sort Leave" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.PresentMarkingDuration : "Present Marking Duration" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.MaxWorkingForHalfDay : "Maximum Working For Half Day" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.MaxWorkingForSortDay : "Maximum Working For Sort Day	" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.MarkHalfDayAfter : "Mark Half Day After" )
                </th>
                <th>
                    @((Session["LangType"].ToString() == "A") ? @IntegratedAttendanceSystem.Resources.Language.MarkHalfDayBefore : "Mark Half Day Before" )
                </th>
            </tr>
        </thead>
        <tbody class="tbody"></tbody>
    </table>

    <div class="container">
        @*<div class="col-md-6">
                <div class="form-group">
                    <label for="Company">Company*</label>
                    <select class="form-control" id="ddlCompany1" name="Company"></select>
                </div>
            </div>*@
        @*<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" onclick="clearTextBox();">Add New Skills</button><br /><br />*@
        @*<button type="button" class="btn btn-primary" id="btnAdd">Add New</button><br /><br />*@
        <!--<table class="table table-bordered" id="tblreport" style="width:100%">
        <tbody>
            <tr>
                <td style="width:100%;">-->
        @*<label><input id="1" type="radio" name="optradio" checked> Job Request by HOD</label>*@
        <!--<div id="example" style="text-align: center; align-items:flex-end">

        </div>-->
        @*<label><input id="2" type="radio" name="optradio"> Age Group Master</label>*@
        <!--</td>
                </tr>
            </tbody>
        </table>-->
    </div>
</body>
</html>